name: CI build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'
    - name: Run vet
      run:  |
             go vet .
    - name: Build program
      run:  |
             go build .
    - name: Run tests
      run:  |
             go test ./...
