name: Automated release
on:
  release:
    types: [published]
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goarch: amd64
        goos: linux
  release-linux-arm:
    name: release linux/arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goarch: arm
        goos: linux
